ViaCepWebMVc/Models/ErrorViewModel.cs
namespace ViaCepWebMVc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ViaCepWebMVc/Models/ViaCepResponse .cs
namespace ViaCepWebMVc.Models
{
    public class ViaCepResponse 
    {
    public string? Cep {get; set;}
    public string? Logradouro {get; set;}
    public string? Complemento {get; set;}
    public string? Unidade {get; set;}
    public string? Bairro {get; set;}
    public string? Localidade {get; set;}
    public string? Uf {get; set;}
    public string? Estado {get; set;}
    public string? Regiao {get; set;}
    public string? Ibge {get; set;}
    public string? Gia {get; set;}
    public string? Ddd {get; set;}
    public string? Siafi {get; set;} 
    }
}

ViaCepWebMVc/Controllers/CepController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using ViaCepWebMVc.Models;

namespace ViaCepWebMVc.Controllers
{
    public class CepController : Controller
    {
        private readonly HttpClient _httpClient;

        public CepController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient("ViaCepAPI");
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View("Index");
        }

        [HttpPost]
        public async Task<IActionResult> BuscarCep(string cep)
        {
            if (string.IsNullOrWhiteSpace(cep)) 
            {
                ViewBag.Error = "Por favor, insira um CEP válido.";
                return View("Index");
            }

            var response = await _httpClient.GetAsync($"http://localhost:5087/Cep/{cep}");

            if (!response.IsSuccessStatusCode)
            {
                ViewBag.Error = "CEP não encontrado ou inválido.";
                return View("Index");
            }

            var jsonResponse = await response.Content.ReadAsStringAsync(); //retornara o json com os dados da API
            
            // vai deserelizar o json para objeto ignorando diferenças de letras maisculas e minusculas 
            var dadosCep = JsonSerializer.Deserialize<ViaCepResponse>(jsonResponse, new JsonSerializerOptions 
            {
                PropertyNameCaseInsensitive = true
            });

            // Passando os dados para a View com um ViewModel ou ViewBag
            ViewBag.Cep = dadosCep;
            return View("Index");
        }


        [HttpPost]
        public async Task<IActionResult> ObterCep(string sigla, string cidade, string endereco)
        {
            if (string.IsNullOrWhiteSpace(sigla) && string.IsNullOrWhiteSpace(cidade) && string.IsNullOrWhiteSpace(endereco))
            {
                ViewBag.Error = "Por favor, insira um CEP válido.";
                return View("Index");
            }
            
            var response = await _httpClient.GetAsync($"http://localhost:5087/Cep/{sigla}/{cidade}/{endereco}");
            
            if (!response.IsSuccessStatusCode)
            {
                ViewBag.Error = "Dados não encontrados.";
                return View("Index");
            }
            
            var jsonResponse = await response.Content.ReadAsStringAsync();
            
            var dadosEndereco = JsonSerializer.Deserialize<ViaCepResponse>(jsonResponse, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

            // Passando os dados para a View com um ViewModel ou ViewBag
            ViewBag.Endereco = dadosEndereco;
            return View("Index");
            
        }
    }
}

ViaCepWebMVc/Views/Cep/Index.cshtml
@model ViaCepResponse

@{
    ViewData["Title"] = "Página Inicial";
}


<div class="main-section">
    <h2 class="title-color">Buscar CEP</h2>
    <br/>

    <form method="post" action="/Cep/BuscarCep">
        <input type="text" name="cep" placeholder="Digite o CEP" required />
        <button type="submit">Buscar</button>
    </form>

    @if (ViewBag.Error != null)
    {
        <p style="color: red;">@ViewBag.Error</p>
    }

    @if (ViewBag.Cep != null)
    {
        <div style="margin-top: 20px;">
            <h3 class="title-color">Dados do Endereço:</h3>
            <br/>
            <p><strong>CEP:</strong> @ViewBag.Cep.Cep</p>
            <p><strong>Logradouro:</strong> @ViewBag.Cep.Logradouro</p>
            <p><strong>Complemento:</strong> @ViewBag.Cep.Complemento</p>
            <p><strong>Unidade: </strong> @ViewBag.Cep.Unidade</p>
            <p><strong>Bairro: </strong> @ViewBag.Cep.Bairro</p>
            <p><strong>Localidade: </strong> @ViewBag.Cep.Localidade</p>
            <p><strong>Uf: </strong> @ViewBag.Cep.Uf</p>
            <p><strong>Estado: </strong> @ViewBag.Cep.Estado</p>
            <p><strong>Região: </strong> @ViewBag.Cep.Regiao</p>
            <p><strong>Ibge: </strong> @ViewBag.Cep.Ibge</p>
            <p><strong>Gia: </strong> @ViewBag.Cep.Gia</p>
            <p><strong>Ddd: </strong> @ViewBag.Cep.Ddd</p>
            <p><strong>Siafi: </strong> @ViewBag.Cep.Siafi</p>
        </div>
    }
    
    <br>

    <form method="post" action="/Cep/ObterCep">
        <input type="text" name="sigla" placeholder="Digite a sigla da cidade ou estado " required />
        <input type="text" name="cidade" placeholder="Digite a cidade ou estado " required />
        <input type="text" name="endereco" placeholder="Digite a rua " required />
        <button type="submit">Buscar</button>
    </form>

    @if (ViewBag.Error != null)
    {
        <p style="color: red;">@ViewBag.Error</p>
    }

    @if (ViewBag.Endereco != null)
    {
        <div style="margin-top: 20px;">
            <h3 class="title-color">Dados do Endereço:</h3>
            <br/>
            <p><strong>CEP:</strong> @ViewBag.Endereco.Cep</p>
            <p><strong>Logradouro:</strong> @ViewBag.Endereco.Logradouro</p>
            <p><strong>Complemento:</strong> @ViewBag.Endereco.Complemento</p>
            <p><strong>Unidade: </strong> @ViewBag.Endereco.Unidade</p>
            <p><strong>Bairro: </strong> @ViewBag.Endereco.Bairro</p>
            <p><strong>Localidade: </strong> @ViewBag.Endereco.Localidade</p>
            <p><strong>Uf: </strong> @ViewBag.Endereco.Uf</p>
            <p><strong>Estado: </strong> @ViewBag.Endereco.Estado</p>
            <p><strong>Região: </strong> @ViewBag.Endereco.Regiao</p>
            <p><strong>Ibge: </strong> @ViewBag.Endereco.Ibge</p>
            <p><strong>Gia: </strong> @ViewBag.Endereco.Gia</p>
            <p><strong>Ddd: </strong> @ViewBag.Endereco.Ddd</p>
            <p><strong>Siafi: </strong> @ViewBag.Endereco.Siafi</p>
        </div>
    }
    
</div>

ViaCepWebMVc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Buscar CEP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ViaCepWebMVc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Cep" asp-action="Index">Buscar CEP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cep" asp-action="Index">Home</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Buscar CEP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>